name = "TSPLIB"
uuid = "b1c258e7-59ae-4b06-a547-f10871db1548"
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Match = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
